### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by masaeedu** [malkapathi/MTE544-ROS-Labs#1]
Hi there. Typically when you fork someone's project and modify it, it is good etiquette to include an acknowledgement of the work you're building on, instead of slapping on a "Written and edited by \<me\>" onto the code.

This codebase was forked from https://github.com/masaeedu/me597

**Comment by malkapathi** [comment]
Hey,
Sorry about that,  I'm new to github so i didn't  know the ethics for it. I'll add acknowledgement right away.
